# Generated manually on 2026-09-08
#
# project_info 테이블은 rounds/project_views.py의 raw SQL로 먼저 도입되어
# 공유 Postgres에 이미 존재한다(이미 존재하는 스키마: id/name/description/
# team_start/team_end/evaluationround_id, teams_info_* 제약조건).
#
# 이 마이그레이션은:
#   1) state_operations로 Django 마이그레이션 상태에 ProjectInfo 모델을
#      등록하여 `makemigrations --check`가 더 이상 drift를 보고하지 않게 하고,
#   2) database_operations로 `CREATE TABLE IF NOT EXISTS`를 실행하여
#      - 이미 테이블이 있는 공유/운영 Postgres에서는 아무 일도 하지 않고
#      - CI처럼 매번 새로 뜨는 빈 Postgres(테스트 DB)에는 실제 테이블이
#        생성되도록 한다.
#
# 기존 운영 테이블의 스키마를 변경하지 않으므로 안전하게 적용할 수 있다.

import django.db.models.deletion
from django.db import migrations, models

CREATE_PROJECT_INFO_SQL = """
CREATE TABLE IF NOT EXISTS public.project_info (
    id int8 GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
    ) NOT NULL,
    team_start date NULL,
    team_end date NULL,
    evaluationround_id int8 NOT NULL,
    name varchar(200) NULL,
    description text NULL,
    CONSTRAINT teams_info_pkey PRIMARY KEY (id),
    CONSTRAINT teams_info_team_window_valid CHECK (
        (
            (team_start IS NULL AND team_end IS NULL)
            OR (
                team_start IS NOT NULL
                AND team_end IS NOT NULL
                AND team_start < team_end
            )
        )
    ),
    CONSTRAINT teams_info_evaluationround_fk FOREIGN KEY (evaluationround_id)
        REFERENCES public.rounds_evaluationround(id) ON DELETE CASCADE
);
"""

DROP_PROJECT_INFO_SQL = "DROP TABLE IF EXISTS public.project_info;"


# SQLite is used only by the isolated QA configuration.
CREATE_PROJECT_INFO_SQLITE_SQL = """
CREATE TABLE IF NOT EXISTS project_info (
    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    team_start date NULL,
    team_end date NULL,
    evaluationround_id bigint NOT NULL,
    name varchar(200) NULL,
    description text NULL,
    CONSTRAINT teams_info_team_window_valid CHECK (
        (team_start IS NULL AND team_end IS NULL)
        OR (team_start IS NOT NULL AND team_end IS NOT NULL AND team_start < team_end)
    ),
    CONSTRAINT teams_info_evaluationround_fk FOREIGN KEY (evaluationround_id)
        REFERENCES rounds_evaluationround(id) ON DELETE CASCADE
);
"""


def create_project_info(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(CREATE_PROJECT_INFO_SQL)
    elif vendor == "sqlite":
        schema_editor.execute(CREATE_PROJECT_INFO_SQLITE_SQL)
    else:
        raise NotImplementedError(f"Unsupported database vendor: {vendor}")


def drop_project_info(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(DROP_PROJECT_INFO_SQL)
    elif vendor == "sqlite":
        schema_editor.execute("DROP TABLE IF EXISTS project_info;")
    else:
        raise NotImplementedError(f"Unsupported database vendor: {vendor}")


class Migration(migrations.Migration):
    dependencies = [
        ("rounds", "0006_alter_evaluationround_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ProjectInfo",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "description",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "team_start",
                            models.DateField(blank=True, null=True),
                        ),
                        (
                            "team_end",
                            models.DateField(blank=True, null=True),
                        ),
                        (
                            "evaluationround",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="project_infos",
                                to="rounds.evaluationround",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "프로젝트 회차",
                        "verbose_name_plural": "프로젝트 회차 목록",
                        "db_table": "project_info",
                    },
                ),
                migrations.AddConstraint(
                    model_name="projectinfo",
                    constraint=models.CheckConstraint(
                        check=(
                            (models.Q(team_start__isnull=True) & models.Q(team_end__isnull=True))
                            | (
                                models.Q(team_start__isnull=False)
                                & models.Q(team_end__isnull=False)
                                & models.Q(team_start__lt=models.F("team_end"))
                            )
                        ),
                        name="teams_info_team_window_valid",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(create_project_info, drop_project_info),
            ],
        ),
    ]
