# Generated by Django 5.2.17 on 2026-09-15 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bug_reports.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="오류 내용")),
                (
                    "page_url",
                    models.CharField(blank=True, max_length=1000, verbose_name="발생 페이지"),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        storage=bug_reports.models.report_storage,
                        upload_to=bug_reports.models.screenshot_path,
                        verbose_name="캡처 이미지",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "접수"),
                            ("in_progress", "확인 중"),
                            ("resolved", "해결 완료"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="처리 답변")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="신고일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_bug_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
