# Generated by Django 5.2.17 on 2026-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assignmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmaterial',
            name='file_name',
            field=models.CharField(blank=True, help_text='원본 파일명 (kind=FILE, 다운로드 시 Content-Type/파일명 복원용)', max_length=255),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='바이트 (kind=FILE)'),
        ),
    ]
