# Generated by Django 5.2.17 on 2026-09-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True, help_text='accounts_user.id 참조, FK 아님')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lms_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_id', 'read_at'], name='lms_notif_recipient_read_idx')],
            },
        ),
    ]
