# Generated by Django 5.2.17 on 2026-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsnotification',
            name='target_type',
            field=models.CharField(blank=True, help_text='link이 가리키는 대상 종류(assignment/lesson/submission). 클릭 시 삭제 여부 확인용, FK 아님', max_length=20),
        ),
        migrations.AddField(
            model_name='lmsnotification',
            name='target_id',
            field=models.IntegerField(blank=True, help_text='target_type 대상의 pk, FK 아님', null=True),
        ),
    ]
