# Generated by Django 5.2.7 on 2026-09-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_muted_email_categories"),
        ("notifications", "0004_slackidentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackidentity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="slackidentity",
            name="slack_display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="slackidentity",
            name="slack_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="slackidentity",
            name="slack_user_id",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="slackidentity",
            name="synced_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="slackidentity",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slack_identity",
                to="accounts.user",
            ),
        ),
    ]
