# Generated by Django 5.2.17 on 2026-09-03 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vector",
                    models.JSONField(
                        help_text="숫자 목록 형태로 저장 (예: [0.12, -0.4, ...])",
                        verbose_name="특징 벡터",
                    ),
                ),
                (
                    "source_image_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="profile_image가 바뀌었는지 확인용",
                        max_length=255,
                        verbose_name="계산에 사용한 사진 파일명",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="계산 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="갱신 일시")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_embedding",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "얼굴 특징 벡터",
                "verbose_name_plural": "얼굴 특징 벡터 목록",
            },
        ),
    ]
